### ISSUE TITLE
Cannot open database

### ISSUE THREAD

**Issue by clupasq** [udger/test-data#1]
I cannot use the `data_v3/udgerdb_v3.dat` file from this repository with the .NET client. I get the following error:

> Test 'M:ConsoleTest.Program.Main(System.String[])' failed: file is encrypted or is not a database
> file is encrypted or is not a database
>   System.Data.SQLite.SQLiteException (0x80004005): file is encrypted or is not a database
>   file is encrypted or is not a database
>   DataReader.cs(62,0): at Udger.Parser.DataReader.selectQuery(String query)
>   UdgerParser.cs(106,0): at Udger.Parser.UdgerParser.parseUA(String _userAgent)
>   UdgerParser.cs(73,0): at Udger.Parser.UdgerParser.parse()
>   Program.cs(37,0): at ConsoleTest.Program.Main(String[] args)

**Comment by mallat** [comment]
For sure I have now tested the. The database can be open.
You set the correct path to the directory?
parser.SetDataDir(@"C:\jtmp\dir_name");
Anyway ... this is half empty db, just to test the parser. The full data is available on udger.com

**Comment by clupasq** [comment]
You're right; I had downloaded the file from github using wget and did not specify the raw URL.
Sorry for the trouble!
