### ISSUE TITLE
Update udger test db

### ISSUE THREAD

**Issue by DimaGolomozy** [udger/test-data#2]
I got unit tests that uses the udger db v3 test db to parse a UA to validate that the udger parsing works fine.
but the test db wasnet updated for 2 years.
when I ran it with udger java version `1.1.0` 
parsing the UA: 
`Mozilla/5.0 (Linux; U; Android 4.0.4; sk-sk; Luna TAB474 Build/LunaTAB474) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Safari/534.30`
returns `tablet` in the raw device type.
but when updating to `1.2.1` it returns `smartphone`.
_(only with the test db, when the normal db it works fine)_

any reason way?

**Comment by mallat** [comment]
The db v3 test is only for the test_ua.json and test_ip.json files.
- https://github.com/udger/test-data/blob/master/data_v3/test_ua.json
- https://github.com/udger/test-data/blob/master/data_v3/test_ip.json

**Comment by DimaGolomozy** [comment]
Well I am using the same UA from the DB.
https://github.com/udger/test-data/blob/907bb77284b4b0928187e0765b951ba154f013ce/data_v3/test_ua.json#L154
and in your results it's also `tablet` 
but with version `1.2.1` its smartphone.
so any reason way?
